import React from 'react'
import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import { Download, FileText, Calendar, Target, Brain, Lightbulb } from 'lucide-react'
import { Button } from './ui/button'
import { PaperAnalysis } from '../types'
import { formatDate, formatConfidence } from '../lib/utils'

interface ReportGeneratorProps {
  analysis: PaperAnalysis
  onDownload?: () => void
}

export function ReportGenerator({ analysis, onDownload }: ReportGeneratorProps) {
  const generatePDF = async () => {
    try {
      // Create PDF
      const pdf = new jsPDF()
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      
      // Add header
      pdf.setFontSize(20)
      pdf.setFont('helvetica', 'bold')
      pdf.text('IntelliInsight Analysis Report', 20, 30)
      
      // Add branding line
      pdf.setFontSize(10)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(100, 100, 100)
      pdf.text('Turning Research Papers into Smart Insights', 20, 40)
      
      // Reset text color
      pdf.setTextColor(0, 0, 0)
      
      // Add paper title
      pdf.setFontSize(16)
      pdf.setFont('helvetica', 'bold')
      const titleLines = pdf.splitTextToSize(analysis.title, pageWidth - 40)
      pdf.text(titleLines, 20, 60)
      
      // Add analysis date
      pdf.setFontSize(10)
      pdf.setFont('helvetica', 'normal')
      pdf.text(`Analysis Date: ${formatDate(analysis.uploadDate)}`, 20, 80)
      
      // Add classifications
      let yPosition = 100
      
      // Publication Type
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Publication Type Classification', 20, yPosition)
      
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'normal')
      pdf.text(`Type: ${analysis.type}`, 30, yPosition + 15)
      pdf.text(`Confidence: ${formatConfidence(analysis.typeConfidence)}`, 30, yPosition + 30)
      
      yPosition += 50
      
      // Research Nature
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Research Nature Classification', 20, yPosition)
      
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'normal')
      pdf.text(`Nature: ${analysis.nature}`, 30, yPosition + 15)
      pdf.text(`Confidence: ${formatConfidence(analysis.natureConfidence)}`, 30, yPosition + 30)
      
      yPosition += 50
      
      // Key Evidence
      if (yPosition > pageHeight - 100) {
        pdf.addPage()
        yPosition = 30
      }
      
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Key Evidence Sentences', 20, yPosition)
      
      pdf.setFontSize(10)
      pdf.setFont('helvetica', 'normal')
      
      analysis.evidence.forEach((evidence, index) => {
        yPosition += 20
        
        if (yPosition > pageHeight - 50) {
          pdf.addPage()
          yPosition = 30
        }
        
        const evidenceLines = pdf.splitTextToSize(`${index + 1}. ${evidence}`, pageWidth - 40)
        pdf.text(evidenceLines, 30, yPosition)
        yPosition += evidenceLines.length * 5
      })
      
      // Add footer
      const footerY = pageHeight - 20
      pdf.setFontSize(8)
      pdf.setTextColor(100, 100, 100)
      pdf.text('Generated by IntelliInsight - AI Research Paper Analysis Platform', 20, footerY)
      pdf.text('https://intelliinsight.com', pageWidth - 80, footerY)
      
      // Save PDF
      const fileName = `IntelliInsight_${analysis.title.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`
      pdf.save(fileName)
      
      onDownload?.()
    } catch (error) {
      console.error('Error generating PDF:', error)
      alert('Failed to generate PDF report. Please try again.')
    }
  }

  const getClassificationIcon = (type: string) => {
    if (type === 'Conference') return <Target className="h-4 w-4" />
    if (type === 'Journal') return <FileText className="h-4 w-4" />
    if (type === 'Implementation') return <Brain className="h-4 w-4" />
    return <Lightbulb className="h-4 w-4" />
  }

  return (
    <div className="space-y-4">
      <div className="hidden" id="report-content">
        {/* Hidden div for PDF generation */}
        <div className="p-8 bg-white">
          <div className="text-center mb-8">
            <h1 className="text-2xl font-bold text-gray-900 mb-2">IntelliInsight Analysis Report</h1>
            <p className="text-gray-600">Turning Research Papers into Smart Insights</p>
          </div>
          
          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-semibold mb-2">{analysis.title}</h2>
              <p className="text-gray-600">Analysis Date: {formatDate(analysis.uploadDate)}</p>
            </div>
            
            <div className="grid grid-cols-2 gap-6">
              <div className="p-4 border rounded-lg">
                <div className="flex items-center gap-2 mb-2">
                  {getClassificationIcon(analysis.type)}
                  <h3 className="font-semibold">Publication Type</h3>
                </div>
                <p className="text-lg">{analysis.type}</p>
                <p className="text-sm text-gray-600">Confidence: {formatConfidence(analysis.typeConfidence)}</p>
              </div>
              
              <div className="p-4 border rounded-lg">
                <div className="flex items-center gap-2 mb-2">
                  {getClassificationIcon(analysis.nature)}
                  <h3 className="font-semibold">Research Nature</h3>
                </div>
                <p className="text-lg">{analysis.nature}</p>
                <p className="text-sm text-gray-600">Confidence: {formatConfidence(analysis.natureConfidence)}</p>
              </div>
            </div>
            
            <div>
              <h3 className="font-semibold mb-4">Key Evidence Sentences</h3>
              <div className="space-y-3">
                {analysis.evidence.map((evidence, index) => (
                  <div key={index} className="p-3 bg-gray-50 rounded-lg">
                    <p className="text-sm">{index + 1}. {evidence}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <Button onClick={generatePDF} className="w-full">
        <Download className="h-4 w-4 mr-2" />
        Download PDF Report
      </Button>
    </div>
  )
}